#! /bin/sh
### BEGIN INIT INFO
# Provides:          bds-snmp-adaptor
# Required-Start:    $remote_fs $time
# Required-Stop:     umountnfs $time
# X-Stop-After:      sendsigs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: RtBrick SNMP Adaptor
# Description:       RtBrick SNMP Adaptor
### END INIT INFO

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="BDS SNMP Notification Originator"
NAME=bds-snmp-adaptor

DAEMON=/usr/local/bin/bds-snmp-adaptor
PIDFILE=/run/bds-snmp-adaptor.pid

BDSSNMPRSP=bds-snmp-adaptor
BDSSNMPRSP_OPTIONS="--config /etc/bds-snmp-adaptor/bds-snmp-adaptor.yml --pidfile $PIDFILE"

SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Define LSB log_* functions.
. /lib/lsb/init-functions

do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   other if daemon could not be started or a failure occured
	start-stop-daemon --start --background --quiet --pidfile $PIDFILE --exec $DAEMON -- $BDSSNMPRSP_OPTIONS
}

do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   other if daemon could not be stopped or a failure occurred
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --exec $DAEMON
}

#
# Tell bds-snmp-adaptor to close all open files
#
do_rotate() {
	start-stop-daemon --stop --signal HUP --quiet --pidfile $PIDFILE --exec $DAEMON
}

sendsigs_omit() {
	OMITDIR=/run/sendsigs.omit.d
	mkdir -p $OMITDIR
	ln -sf $PIDFILE $OMITDIR/bds-snmp-adaptor
}

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" "$BDSSNMPRSP"
	do_start
	case "$?" in
		0) sendsigs_omit
		   log_end_msg 0 ;;
		1) log_progress_msg "already started"
		   log_end_msg 0 ;;
		*) log_end_msg 1 ;;
	esac

	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$BDSSNMPRSP"
	do_stop
	case "$?" in
		0) log_end_msg 0 ;;
		1) log_progress_msg "already stopped"
		   log_end_msg 0 ;;
		*) log_end_msg 1 ;;
	esac

	;;
  rotate)
	log_daemon_msg "Closing open files" "$BDSSNMPRSP"
	do_rotate
	log_end_msg $?
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  try-restart)
	$0 status >/dev/null 2>&1 && $0 restart
	;;
  status)
	status_of_proc -p $PIDFILE $DAEMON $BDSSNMPRSP && exit 0 || exit $?
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|rotate|restart|force-reload|try-restart|status}" >&2
	exit 3
	;;
esac

:
